/**
 * Assembles css/tokens.css and json/tokens.json from the token source.
 * Run with: npm run gen -w @perfect/tokens  (Node 23+ runs .ts natively)
 *
 * This file only ORDERS and formats declarations. Every value, and the logic
 * that turns it into a `--perfect-*` declaration, lives in the matching domain
 * module (type.ts, space.ts, color.ts, ...). To change a base value, open that
 * one file — this orchestrator does not need to change.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { accentOptions, accentDecls, rampDecls } from './color.ts';
import { typographyDecls, sansFonts, monoFonts, sansFontDecls, monoFontDecls, type SansFont, type MonoFont } from './type.ts';
import { spacingDecls } from './space.ts';
import { radiusDecls } from './radius.ts';
import { sizeDecls } from './size.ts';
import { motionDecls, reducedMotionDecls } from './motion.ts';
import { densityDecls } from './density.ts';
import { effectsDecls, glassDecls } from './effects.ts';
import { layoutDecls } from './layout.ts';
import { shadowDecls } from './elevation.ts';
import { semanticDecls, statusDecls, themeOverrideDecls } from './semantic.ts';

const P = '--perfect';
type Decl = [name: string, value: string];

/** Custom-property lines for a group of declarations, at the given indent. */
const lines = (decls: Decl[], indent: string): string[] =>
  decls.map(([name, value]) => `${indent}${P}-${name}: ${value};`);

/** A labeled group of declarations, or nothing when the group is empty. */
const section = (title: string, decls: Decl[], indent: string): string[] =>
  decls.length ? [`${indent}/* ${title} */`, ...lines(decls, indent), ''] : [];

// ---- :root — universal tokens + the light theme ----------------------------
// Order is presentation only; every custom property resolves regardless of
// where it sits. Grouped by domain so the output reads like the source.
const rootSections: Array<{ title: string; decls: Decl[] }> = [
  { title: 'Typography', decls: typographyDecls() },
  { title: 'Spacing', decls: spacingDecls() },
  { title: 'Radius', decls: radiusDecls() },
  { title: 'Size scale', decls: sizeDecls() },
  { title: 'Motion', decls: motionDecls() },
  { title: 'Density & control sizing', decls: densityDecls('comfortable') },
  { title: 'Effects — blur, glass, hairline', decls: effectsDecls() },
  { title: 'Layout — containers & breakpoints', decls: layoutDecls() },
  { title: 'Color ramps', decls: rampDecls('light') },
  { title: 'Elevation', decls: shadowDecls('light') },
  { title: 'Glass materials', decls: glassDecls('light') },
  { title: 'Semantic aliases', decls: semanticDecls() },
  { title: 'Status aliases', decls: statusDecls() },
  { title: 'Light theme surfaces', decls: themeOverrideDecls('light') },
];

// ---- the dark theme override block (reused for the two dark selectors) ------
const darkBlock = (indent: string): string[] => [
  `${indent}color-scheme: dark;`,
  '',
  ...section('Color ramps', rampDecls('dark'), indent),
  ...section('Elevation', shadowDecls('dark'), indent),
  ...section('Glass materials', glassDecls('dark'), indent),
  ...section('Theme surfaces', themeOverrideDecls('dark'), indent),
];

const out: string[] = ['/* GENERATED by @perfect/tokens — edit src/*.ts and run `npm run gen`. */', ''];

out.push(':root {', '  color-scheme: light;', '');
for (const { title, decls } of rootSections) out.push(...section(title, decls, '  '));
out.push('}', '');

out.push('/* Dark theme — data-theme="dark", or prefers-color-scheme with no explicit light */', '');
out.push("[data-theme='dark'] {", ...darkBlock('  '), '}', '');
out.push(
  '@media (prefers-color-scheme: dark) {',
  "  :root:not([data-theme='light']) {",
  ...darkBlock('    '),
  '  }',
  '}',
  '',
);

out.push('/* Pickable accents — data-accent="name" swaps the accent ramp */', '');
for (const option of accentOptions.slice(1)) {
  out.push(`[data-accent='${option.name}'] {`, ...lines(accentDecls(option, 'light'), '  '), '}', '');
  out.push(`[data-theme='dark'][data-accent='${option.name}'] {`, ...lines(accentDecls(option, 'dark'), '  '), '}', '');
  out.push(
    '@media (prefers-color-scheme: dark) {',
    `  :root:not([data-theme='light'])[data-accent='${option.name}'] {`,
    ...lines(accentDecls(option, 'dark'), '    '),
    '  }',
    '}',
    '',
  );
}

out.push('/* Pickable fonts — data-font swaps the sans family (default inter is the :root value) */', '');
for (const name of Object.keys(sansFonts).slice(1) as SansFont[]) {
  out.push(`[data-font='${name}'] {`, ...lines(sansFontDecls(name), '  '), '}', '');
}

out.push('/* Pickable mono — data-mono swaps the mono family (default jetbrains is the :root value) */', '');
for (const name of Object.keys(monoFonts).slice(1) as MonoFont[]) {
  out.push(`[data-mono='${name}'] {`, ...lines(monoFontDecls(name), '  '), '}', '');
}

out.push('/* Compact density — data-density="compact" */', '');
out.push("[data-density='compact'] {", ...lines(densityDecls('compact'), '  '), '}', '');

out.push('/* Reduced motion */', '');
out.push('@media (prefers-reduced-motion: reduce) {', '  :root {', ...lines(reducedMotionDecls(), '    '), '  }', '}', '');

// ---- write css -------------------------------------------------------------
const css = `${out.join('\n')}\n`;
const cssOut = new URL('../css/tokens.css', import.meta.url);
mkdirSync(new URL('../css/', import.meta.url), { recursive: true });
writeFileSync(cssOut, css);
console.log(`wrote ${cssOut.pathname} (${css.length} bytes)`);

// ---- write the language-agnostic catalog: base name -> value ---------------
// The :root base tokens only; theme overrides live in CSS. Specs resolve here.
const catalog: Record<string, string> = Object.fromEntries(rootSections.flatMap((s) => s.decls));
const jsonOut = new URL('../json/tokens.json', import.meta.url);
mkdirSync(new URL('../json/', import.meta.url), { recursive: true });
writeFileSync(jsonOut, `${JSON.stringify({ prefix: P, tokens: catalog }, null, 2)}\n`);
console.log(`wrote ${jsonOut.pathname} (${Object.keys(catalog).length} tokens)`);
