/**
 * Emits css/tokens.css from the TypeScript token source.
 * Run with: npm run gen -w @perfect/tokens  (Node 23+ runs .ts natively)
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { accentOptions, accentSteps, ramps, rampSteps, type Theme } from './color.ts';
import { space, SPACE_STEPS } from './space.ts';
import { typeScale, fontFamilies, fontWeights } from './type.ts';
import { radii, SCALED_RADII, type RadiusStep } from './radius.ts';
import { shadows } from './elevation.ts';
import { durations, easings, cssEase, type EaseRole } from './motion.ts';
import { controlHeights } from './density.ts';
import { semantic, themeOverrides, statusTokens } from './semantic.ts';
import { blurs, glassTokens, GLASS_SATURATE, HAIRLINE } from './effects.ts';
import { containers, breakpoints } from './layout.ts';

const P = '--perfect';
const lines: string[] = [];
const decl = (name: string, value: string) => lines.push(`  ${P}-${name}: ${value};`);

function rampDecls(theme: Theme): void {
  for (const ramp of ramps) {
    rampSteps(ramp, theme).forEach((color, i) => decl(`${ramp.name}-${i + 1}`, color));
  }
}

function shadowDecls(theme: Theme): void {
  shadows[theme].forEach((s, i) => decl(`shadow-${i}`, s));
}

function darkDecls(indent: string): string[] {
  const out: string[] = ['color-scheme: dark;'];
  const push = (name: string, value: string) => out.push(`${P}-${name}: ${value};`);
  for (const ramp of ramps) {
    rampSteps(ramp, 'dark').forEach((color, i) => push(`${ramp.name}-${i + 1}`, color));
  }
  shadows.dark.forEach((s, i) => push(`shadow-${i}`, s));
  for (const [name, value] of Object.entries(glassTokens.dark)) push(name, value);
  for (const [name, value] of Object.entries(themeOverrides.dark)) push(name, value);
  return out.map((l) => indent + l);
}

lines.push('/* GENERATED by @perfect/tokens — edit src/*.ts and run `npm run gen`. */', '');

// ---- light theme + universal tokens -------------------------------------
lines.push(':root {');
lines.push('  color-scheme: light;');

decl('font-sans', fontFamilies.sans);
decl('font-mono', fontFamilies.mono);
for (const [name, weight] of Object.entries(fontWeights)) decl(`font-weight-${name}`, String(weight));

for (const step of typeScale) {
  decl(`font-size-${step.name}`, step.size.clamp);
  decl(`leading-${step.name}`, String(step.lineHeight));
  decl(`tracking-${step.name}`, step.tracking);
}

for (const n of SPACE_STEPS) decl(`space-${n}`, space[n].clamp);
decl('space-px', '1px');
decl('hairline', HAIRLINE);

decl('radius-scale', '1');
for (const [name, value] of Object.entries(radii)) {
  const scaled = SCALED_RADII.includes(name as RadiusStep);
  decl(`radius-${name}`, scaled ? `calc(${value} * var(${P}-radius-scale))` : value);
}

for (const [name, ms] of Object.entries(durations)) decl(`duration-${name}`, `${ms}ms`);
for (const name of Object.keys(easings)) decl(`ease-${name}`, cssEase(name as EaseRole));

for (const [size, h] of Object.entries(controlHeights.comfortable)) decl(`control-height-${size}`, h);
decl('control-radius', 'var(--perfect-radius-full)');

for (const [name, value] of Object.entries(blurs)) decl(`blur-${name}`, value);
decl('glass-saturate', GLASS_SATURATE);

for (const [name, value] of Object.entries(containers)) decl(`container-${name}`, value);
for (const [name, px] of Object.entries(breakpoints)) decl(`breakpoint-${name}`, `${px}px`);

rampDecls('light');
shadowDecls('light');
for (const [name, value] of Object.entries(glassTokens.light)) decl(name, value);

for (const [name, value] of Object.entries(semantic)) decl(name, value);
for (const [name, value] of Object.entries(statusTokens())) decl(name, value);
for (const [name, value] of Object.entries(themeOverrides.light)) decl(name, value);

lines.push('}', '');

// ---- dark theme ----------------------------------------------------------
lines.push("[data-theme='dark'] {", ...darkDecls('  '), '}', '');
lines.push('@media (prefers-color-scheme: dark) {');
lines.push("  :root:not([data-theme='light']) {", ...darkDecls('    '), '  }', '}', '');

// ---- pickable accents ------------------------------------------------------
// First option is the built-in default (already emitted as the accent ramp).
// Dark variants carry higher specificity, so block order cannot break them.
for (const option of accentOptions.slice(1)) {
  const steps = (theme: Theme, indent: string) =>
    accentSteps(option, theme).map((c, i) => `${indent}${P}-accent-${i + 1}: ${c};`);
  lines.push(`[data-accent='${option.name}'] {`, ...steps('light', '  '), '}', '');
  lines.push(`[data-theme='dark'][data-accent='${option.name}'] {`, ...steps('dark', '  '), '}', '');
  lines.push('@media (prefers-color-scheme: dark) {');
  lines.push(
    `  :root:not([data-theme='light'])[data-accent='${option.name}'] {`,
    ...steps('dark', '    '),
    '  }',
    '}',
    '',
  );
}

// ---- density ---------------------------------------------------------------
lines.push("[data-density='compact'] {");
for (const [size, h] of Object.entries(controlHeights.compact)) decl(`control-height-${size}`, h);
lines.push('}', '');

// ---- reduced motion --------------------------------------------------------
lines.push('@media (prefers-reduced-motion: reduce) {');
lines.push('  :root {');
for (const name of Object.keys(durations)) lines.push(`    ${P}-duration-${name}: 0.01ms;`);
lines.push('  }', '}', '');

const css = lines.join('\n');
const out = new URL('../css/tokens.css', import.meta.url);
mkdirSync(new URL('../css/', import.meta.url), { recursive: true });
writeFileSync(out, css);
console.log(`wrote ${out.pathname} (${css.length} bytes)`);
