import type { ComponentSpec } from '../schema.ts';
import { controlSize, controlSizes, token } from '../vocab.ts';

export const comboboxSizes = controlSizes;

export const comboboxSpec: ComponentSpec = {
  name: 'Combobox',
  id: 'combobox',
  category: 'molecule',
  status: 'draft',
  summary: 'An editable input that filters and commits one option from a portaled listbox.',
  element: 'div',
  anatomy: [
    { name: 'input', description: 'The editable combobox input that retains focus while options are navigated.', required: true },
    { name: 'indicator', description: 'A decorative trailing chevron that indicates available suggestions.' },
    { name: 'menu', description: 'The portaled listbox of filtered options.' },
    { name: 'option', description: 'A selectable option row with an optional supporting description.' },
    { name: 'empty', description: 'The non-selectable result shown when the current query has no matches.' },
    { name: 'hiddenInput', description: 'A hidden form value rendered when name is set.' },
  ],
  props: [
    {
      name: 'options',
      type: 'array',
      required: true,
      description: 'Options available to filter and select.',
      item: {
        type: 'object',
        description: 'A selectable combobox option.',
        fields: [
          { name: 'value', type: 'string', required: true, description: 'Unique submitted value for the option.' },
          { name: 'label', type: 'node', required: true, description: 'Content rendered in the input and option row.' },
          { name: 'textValue', type: 'string', description: 'Plain text used for filtering when label is not a string.' },
          { name: 'description', type: 'node', description: 'Optional muted supporting content below the label.' },
          { name: 'disabled', type: 'boolean', description: 'Prevents the option from being selected.' },
        ],
      },
    },
    { name: 'value', type: 'string', description: 'Controlled selected option value.' },
    { name: 'defaultValue', type: 'string', description: 'Uncontrolled initial selected option value.' },
    { name: 'onValueChange', type: 'handler', description: 'Called when an option is committed.' },
    { name: 'inputValue', type: 'string', description: 'Controlled text shown in the editable input.' },
    { name: 'defaultInputValue', type: 'string', description: 'Uncontrolled initial text shown in the editable input.' },
    { name: 'onInputValueChange', type: 'handler', description: 'Called whenever the editable input text changes.' },
    { name: 'filter', type: 'handler', description: 'Custom predicate that decides whether an option matches the current input text.' },
    { name: 'placeholder', type: 'string', description: 'Hint shown while the input is empty.' },
    { name: 'emptyState', type: 'node', description: 'Content shown when the current query has no matching options.' },
    { name: 'loading', type: 'boolean', default: false, description: 'Marks the listbox busy and shows the localized loading state.' },
    { name: 'size', type: 'enum', values: comboboxSizes, default: 'md', description: 'Control size step.' },
    { name: 'fullWidth', type: 'boolean', default: false, description: 'Stretches the control to its container width.' },
    { name: 'disabled', type: 'boolean', default: false, description: 'Blocks editing and opening the option list.' },
    { name: 'skeleton', type: 'boolean', default: false, description: 'Renders a placeholder with the control geometry.' },
    { name: 'glass', type: 'boolean', default: false, description: 'Uses the frosted glass material for the input surface.' },
    { name: 'name', type: 'string', description: 'Submitted with forms through a hidden input when set.' },
    { name: 'id', type: 'string', description: 'Id for the editable input; falls back to the surrounding Field id.' },
    { name: 'aria-label', type: 'string', description: 'Accessible name when no surrounding Field label is present.' },
  ],
  sizes: [
    controlSize('sm', { paddingInline: token('space-3') }),
    controlSize('md', { paddingInline: token('space-4') }),
    controlSize('lg', { paddingInline: token('space-5') }),
  ],
  defaults: { loading: false, size: 'md', fullWidth: false, disabled: false, skeleton: false, glass: false },
  dimensions: {
    radius: token('radius-lg'),
    optionRadius: token('radius-md'),
    gap: token('space-3'),
    border: token('hairline'),
    menuPadding: token('space-1'),
  },
  states: [
    { name: 'hover', description: 'The input border strengthens when not focused or disabled.', tokens: { border: token('border-strong') } },
    { name: 'focus', description: 'The input border turns to the focus ring with an accent-soft ring.', tokens: { border: token('focus-ring'), ring: token('accent-soft') } },
    { name: 'open', description: 'The portaled listbox fades and scales in from the input edge: a glass-thick panel with a glass border, glass highlight, and shadow-4.', tokens: { background: token('glass-thick'), border: token('glass-border'), highlight: token('glass-highlight'), shadow: token('shadow-4') } },
    { name: 'active', description: 'The keyboard-active option fills with the accent tone.', tokens: { background: token('accent-solid'), text: token('accent-contrast') } },
    { name: 'selected', description: 'On reopen the committed option becomes the active row and takes the accent fill; its value is submitted through the hidden input when name is set.', tokens: { background: token('accent-solid'), text: token('accent-contrast') } },
    { name: 'empty', description: 'A non-selectable localized result appears in the subtle text color when filtering returns no options.', tokens: { text: token('text-subtle') } },
    { name: 'loading', description: 'The listbox exposes aria-busy while result data is loading.' },
    { name: 'disabled', description: 'The input dims and uses the sunken surface.', tokens: { background: token('surface-sunken') } },
    { name: 'invalid', description: 'A surrounding Field error paints a danger border.', tokens: { border: token('danger-border') } },
  ],
  // a 3px accent-soft glow hugging the border, which itself turns focus-ring
  focusRing: { ring: token('accent-soft'), offset: '0' },
  transition: { duration: token('duration-fast'), ease: token('ease-out') },
  tokens: [
    'font-sans', 'space-1', 'space-2', 'space-3', 'space-4', 'space-5', 'space-8', 'space-10',
    'control-height-sm', 'control-height-md', 'control-height-lg',
    'font-size-xs', 'font-size-sm', 'font-size-md', 'leading-sm',
    'radius-md', 'radius-lg', 'hairline',
    'border', 'border-strong', 'focus-ring', 'danger-border',
    'surface', 'surface-sunken', 'text', 'text-muted', 'text-subtle', 'text-disabled',
    'accent-solid', 'accent-soft', 'accent-contrast',
    'glass-regular', 'glass-thick', 'glass-border', 'glass-highlight', 'glass-saturate', 'blur-sm', 'blur-lg', 'shadow-4',
    'duration-fast', 'ease-out',
  ],
  a11y: {
    role: 'combobox',
    focusable: true,
    keyboard: [
      { keys: 'ArrowDown, ArrowUp', action: 'Opens the listbox or moves the active enabled option while focus stays in the input.' },
      { keys: 'Home, End', action: 'Moves the active option to the first or last enabled filtered result.' },
      { keys: 'Enter', action: 'Commits the active option and closes the listbox.' },
      { keys: 'Escape', action: 'Closes the listbox without changing the selected value.' },
      { keys: 'Tab', action: 'Closes the listbox and continues normal tab navigation.' },
    ],
    notes: [
      'Follows the WAI-ARIA editable combobox pattern: focus stays on the input and aria-activedescendant identifies the active option.',
      'The listbox portals to document.body, flips and clamps through the shared anchored-position engine, and closes on an outside press.',
      'Reads id, aria-describedby, and aria-invalid from a surrounding Field when present.',
    ],
  },
  motion: {
    description: 'The suggestion panel fades and scales in from the input edge; motion is disabled when reduced motion is preferred.',
    transition: { speed: 'fast', ease: 'out' },
  },
};