import type { ComponentSpec } from '../schema.ts';
import { token } from '../vocab.ts';

export const dataGridSpec: ComponentSpec = {
  name: 'DataGrid',
  id: 'data-grid',
  category: 'organism',
  status: 'stable',
  summary:
    'A column-driven data grid with client sorting, row selection, loading and empty states, responsive overflow, and a roving-focus keyboard grid - the interactive counterpart to the static Table.',
  element: 'table',
  anatomy: [
    { name: 'grid', description: 'The role="grid" table that owns the roving tabindex and keyboard model.', required: true },
    { name: 'header', description: 'The header row of role="columnheader" cells.', required: true },
    { name: 'sortIndicator', description: 'The direction glyph on a sortable header; reflects aria-sort ascending, descending, or none.' },
    { name: 'selectionColumn', description: 'The optional leading column of row checkboxes with a select-all header checkbox.' },
    { name: 'row', description: 'A role="row" of role="gridcell" cells; carries aria-selected when selectable.', required: true },
    { name: 'cell', description: 'A role="gridcell"; a single roving-focus stop rendered from the column render or the raw row value.', required: true },
    { name: 'emptyState', description: 'A single spanning cell shown when there are no rows and not loading.' },
    { name: 'loading', description: 'Skeleton rows shown while loading, keeping the header and column widths.' },
  ],
  props: [
    {
      name: 'columns',
      type: 'array',
      required: true,
      description: 'The column definitions that drive the header and cell rendering.',
      item: {
        type: 'object',
        description: 'One column.',
        fields: [
          { name: 'key', type: 'string', required: true, description: 'Matches a key on each row and identifies the column for sorting.' },
          { name: 'header', type: 'node', required: true, description: 'Header content.' },
          { name: 'align', type: 'enum', values: ['start', 'center', 'end'], description: 'Cell text alignment; defaults to start.' },
          { name: 'sortable', type: 'boolean', description: 'Makes the header an activatable three-state sort control.' },
          { name: 'width', type: 'string', description: 'A fixed or minimum column width, e.g. 12rem.' },
          { name: 'render', type: 'handler', description: 'Custom cell renderer (row, rowIndex); defaults to String(row[key]).' },
          { name: 'sortValue', type: 'handler', description: 'Custom comparable value for sorting; defaults to row[key].' },
        ],
      },
    },
    {
      name: 'data',
      type: 'array',
      required: true,
      description: 'The rows to render; each must carry a stable id.',
      item: {
        type: 'object',
        description: 'One row.',
        fields: [
          { name: 'id', type: 'string', required: true, description: 'Stable row identity (string or number), reported by selection.' },
        ],
      },
    },
    { name: 'aria-label', type: 'string', required: true, description: 'Accessible name for the grid.' },
    { name: 'sort', type: 'object', description: 'Controlled active sort: { columnKey, direction }, or null for unsorted.', fields: [
      { name: 'columnKey', type: 'string', required: true, description: 'The sorted column key.' },
      { name: 'direction', type: 'enum', values: ['asc', 'desc'], required: true, description: 'Sort direction.' },
    ] },
    { name: 'defaultSort', type: 'object', description: 'Initial sort when uncontrolled, or null.', fields: [
      { name: 'columnKey', type: 'string', required: true, description: 'The sorted column key.' },
      { name: 'direction', type: 'enum', values: ['asc', 'desc'], required: true, description: 'Sort direction.' },
    ] },
    { name: 'onSortChange', type: 'handler', description: 'Called with the next sort (or null) when a sortable header cycles.' },
    { name: 'manualSort', type: 'boolean', default: false, description: 'Skip built-in client sorting; report sort changes and render data as given (server sorting).' },
    { name: 'selectable', type: 'boolean', default: false, description: 'Render a leading checkbox column with select-all in the header.' },
    { name: 'selectedIds', type: 'array', description: 'Controlled list of selected row ids.', item: { type: 'string', description: 'A selected row id (string or number).' } },
    { name: 'defaultSelectedIds', type: 'array', description: 'Initially selected row ids when uncontrolled.', item: { type: 'string', description: 'A selected row id (string or number).' } },
    { name: 'onSelectionChange', type: 'handler', description: 'Called with the next full list of selected ids whenever selection changes.' },
    { name: 'loading', type: 'boolean', default: false, description: 'Show skeleton rows and mark the grid aria-busy.' },
    { name: 'loadingRows', type: 'number', default: 5, description: 'How many skeleton rows to show while loading.' },
    { name: 'emptyState', type: 'node', description: 'Content shown when there are no rows and not loading.' },
    { name: 'density', type: 'enum', values: ['comfortable', 'compact'], default: 'comfortable', description: 'Row rhythm; compact trims vertical padding for data-dense views.' },
    { name: 'stickyHeader', type: 'boolean', default: false, description: 'Pin the header row while the body scrolls vertically.' },
    { name: 'maxHeight', type: 'string', description: 'Cap the body height and scroll vertically; pairs with stickyHeader.' },
    { name: 'skeleton', type: 'boolean', default: false, description: 'Renders a placeholder with the component exact geometry.' },
  ],
  defaults: {
    manualSort: false,
    selectable: false,
    loading: false,
    loadingRows: 5,
    density: 'comfortable',
    stickyHeader: false,
    skeleton: false,
  },
  dimensions: {
    radius: token('radius-md'),
    border: token('hairline'),
    cellPaddingInline: token('space-4'),
    cellPaddingBlock: token('space-3'),
    compactPaddingBlock: token('space-2'),
    emptyPaddingBlock: token('space-8'),
    headerGap: token('space-2'),
  },
  states: [
    { name: 'selected', description: 'A selected row wears the accent soft tint.', tokens: { background: '$accent-soft' } },
    { name: 'sorted', description: 'The active sortable header and its indicator take the accent text color.', tokens: { text: '$accent-text' } },
    { name: 'hover', description: 'Pointer over a sortable header.', tokens: { text: '$accent-text' } },
    { name: 'loading', description: 'Skeleton rows stand in while data loads; the grid is aria-busy.' },
  ],
  focusRing: { ring: token('focus-ring'), offset: '-2px' },
  transition: { duration: token('duration-fast'), ease: token('ease-out') },
  tokens: [
    'surface', 'text', 'text-muted', 'text-subtle', 'border', 'hairline',
    'radius-md', 'font-size-sm', 'space-2', 'space-3', 'space-4', 'space-8',
    'accent-soft', 'accent-text', 'focus-ring', 'duration-fast', 'ease-out',
  ],
  a11y: {
    role: 'grid',
    focusable: true,
    keyboard: [
      { keys: 'ArrowRight, ArrowLeft', action: 'Moves cell focus one column right or left, clamped to the grid edges.' },
      { keys: 'ArrowDown, ArrowUp', action: 'Moves cell focus one row down or up, including into and out of the header row.' },
      { keys: 'Home, End', action: 'Moves cell focus to the first or last cell in the row.' },
      { keys: 'Ctrl+Home, Ctrl+End', action: 'Moves cell focus to the first cell of the header or the last cell of the last row.' },
      { keys: 'Enter, Space', action: 'On a sortable header cell, cycles its sort ascending, descending, then unsorted.' },
      { keys: 'Space', action: 'On a selection cell, toggles that row; on the select-all header, toggles every row.' },
    ],
    notes: [
      'The host is a role="grid" table of role="row" rows with role="columnheader" and role="gridcell" cells; it exposes aria-rowcount, aria-colcount, and per-cell aria-rowindex and aria-colindex.',
      'One roving tabindex spans the cells: exactly one cell sits in the tab order, and arrow keys move it across the header and body.',
      'Sortable headers carry aria-sort (ascending, descending, or none) and cycle three states; sorting is client-side unless manualSort defers it to the parent.',
      'Selection is multi-select through a leading checkbox column; rows report aria-selected and the header checkbox shows an indeterminate dash on a partial selection.',
      'The grid scrolls horizontally for overflow and, with maxHeight, vertically under a sticky header.',
    ],
  },
  motion: {
    description: 'The sort indicator crossfades its color on a token transition; respects reduced motion.',
    transition: { speed: 'fast', ease: 'out' },
  },
};
