import type { ComponentSpec } from '../schema.ts';
import { controlSize, controlSizes, token } from '../vocab.ts';

export const multiSelectSizes = controlSizes;

export const multiSelectSpec: ComponentSpec = {
  name: 'MultiSelect',
  id: 'multi-select',
  category: 'molecule',
  status: 'draft',
  summary: 'An editable multi-value combobox that filters options, renders selected values as removable tags, and submits repeated form values.',
  element: 'div',
  anatomy: [
    { name: 'control', description: 'The input-like shell that contains selected tags, editable input, and indicator.', required: true },
    { name: 'tag', description: 'A selected value rendered as an inline tag.' },
    { name: 'tagRemove', description: 'The button that removes an individual selected tag.' },
    { name: 'input', description: 'The editable combobox input that retains focus while options are navigated.', required: true },
    { name: 'indicator', description: 'A decorative trailing chevron that indicates available suggestions.' },
    { name: 'menu', description: 'The portaled multi-select listbox of filtered options.' },
    { name: 'option', description: 'A selectable option row with optional supporting description and selected check.' },
    { name: 'empty', description: 'The non-selectable result shown when the current query has no matches.' },
    { name: 'hiddenInput', description: 'One hidden form value per selected option when name is set.' },
  ],
  props: [
    {
      name: 'options',
      type: 'array',
      required: true,
      description: 'Options available to filter and toggle.',
      item: {
        type: 'object',
        description: 'A selectable multi-select option.',
        fields: [
          { name: 'value', type: 'string', required: true, description: 'Unique submitted value for the option.' },
          { name: 'label', type: 'node', required: true, description: 'Content rendered in the selected tag and option row.' },
          { name: 'textValue', type: 'string', description: 'Plain text used for filtering when label is not a string.' },
          { name: 'description', type: 'node', description: 'Optional muted supporting content below the option label.' },
          { name: 'disabled', type: 'boolean', description: 'Prevents the option from being toggled.' },
        ],
      },
    },
    { name: 'value', type: 'array', item: { type: 'string', description: 'One controlled selected option value.' }, description: 'Controlled selected option values.' },
    { name: 'defaultValue', type: 'array', item: { type: 'string', description: 'One uncontrolled selected option value.' }, description: 'Uncontrolled initial selected option values.' },
    { name: 'onValueChange', type: 'handler', description: 'Called whenever the selected value array changes.' },
    { name: 'inputValue', type: 'string', description: 'Controlled text shown in the editable input.' },
    { name: 'defaultInputValue', type: 'string', description: 'Uncontrolled initial text shown in the editable input.' },
    { name: 'onInputValueChange', type: 'handler', description: 'Called whenever the editable input text changes.' },
    { name: 'filter', type: 'handler', description: 'Custom predicate that decides whether an option matches the current input text.' },
    { name: 'placeholder', type: 'string', description: 'Hint shown while no selected tags or query are present.' },
    { name: 'emptyState', type: 'node', description: 'Content shown when the current query has no matching options.' },
    { name: 'loading', type: 'boolean', default: false, description: 'Marks the listbox busy and shows the localized loading state.' },
    { name: 'size', type: 'enum', values: multiSelectSizes, default: 'md', description: 'Control size step.' },
    { name: 'fullWidth', type: 'boolean', default: false, description: 'Stretches the control to its container width.' },
    { name: 'disabled', type: 'boolean', default: false, description: 'Blocks editing, opening, and tag removal.' },
    { name: 'skeleton', type: 'boolean', default: false, description: 'Renders a placeholder with the control geometry.' },
    { name: 'glass', type: 'boolean', default: false, description: 'Uses the frosted glass material for the control surface.' },
    { name: 'name', type: 'string', description: 'Submits one hidden input for each selected value when set.' },
    { name: 'id', type: 'string', description: 'Id for the editable input; falls back to the surrounding Field id.' },
    { name: 'aria-label', type: 'string', description: 'Accessible name when no surrounding Field label is present.' },
  ],
  sizes: [
    controlSize('sm', { paddingInline: token('space-2') }),
    controlSize('md', { paddingInline: token('space-3') }),
    controlSize('lg', { paddingInline: token('space-4') }),
  ],
  defaults: { loading: false, size: 'md', fullWidth: false, disabled: false, skeleton: false, glass: false },
  dimensions: {
    radius: token('radius-lg'),
    tagRadius: token('radius-full'),
    optionRadius: token('radius-md'),
    gap: token('space-1'),
    border: token('hairline'),
    menuPadding: token('space-1'),
  },
  states: [
    { name: 'hover', description: 'The control border strengthens when not focused or disabled.', tokens: { border: token('border-strong') } },
    { name: 'focus', description: 'The control border turns to the focus ring with an accent-soft ring.', tokens: { border: token('focus-ring'), ring: token('accent-soft') } },
    { name: 'open', description: 'The portaled listbox fades and scales in from the control edge: a glass-thick panel with a glass border, glass highlight, and shadow-4.', tokens: { background: token('glass-thick'), border: token('glass-border'), highlight: token('glass-highlight'), shadow: token('shadow-4') } },
    { name: 'active', description: 'The keyboard-active option fills with the accent tone.', tokens: { background: token('accent-solid'), text: token('accent-contrast') } },
    { name: 'selected', description: 'A selected option (when not the active row) tints accent-soft and shows an accent check; selected values render as accent-soft tags in the control.', tokens: { background: token('accent-soft'), check: token('accent-solid') } },
    { name: 'empty', description: 'A non-selectable localized result appears in the subtle text color when filtering returns no options.', tokens: { text: token('text-subtle') } },
    { name: 'loading', description: 'The listbox exposes aria-busy while result data is loading.' },
    { name: 'disabled', description: 'The control dims, uses the sunken surface, and blocks tag removal.', tokens: { background: token('surface-sunken') } },
    { name: 'invalid', description: 'A surrounding Field error paints a danger border.', tokens: { border: token('danger-border') } },
  ],
  // a 3px accent-soft glow hugging the control border, which itself turns
  // focus-ring while the inner input holds focus (focus-within)
  focusRing: { ring: token('accent-soft'), offset: '0' },
  transition: { duration: token('duration-fast'), ease: token('ease-out') },
  tokens: [
    'font-sans', 'space-1', 'space-2', 'space-3', 'space-4', 'space-5', 'space-8', 'space-10',
    'control-height-sm', 'control-height-md', 'control-height-lg',
    'font-size-xs', 'font-size-sm', 'font-size-md', 'leading-sm',
    'radius-md', 'radius-lg', 'radius-full', 'hairline',
    'border', 'border-strong', 'focus-ring', 'danger-border',
    'surface', 'surface-sunken', 'text', 'text-muted', 'text-subtle', 'text-disabled',
    'accent-solid', 'accent-soft', 'accent-contrast',
    'glass-regular', 'glass-thick', 'glass-border', 'glass-highlight', 'glass-saturate', 'blur-sm', 'blur-lg', 'shadow-4',
    'duration-fast', 'ease-out',
  ],
  a11y: {
    role: 'combobox',
    focusable: true,
    keyboard: [
      { keys: 'ArrowDown, ArrowUp', action: 'Opens the listbox or moves the active enabled option while focus stays in the input.' },
      { keys: 'Home, End', action: 'Moves the active option to the first or last enabled filtered result.' },
      { keys: 'Enter', action: 'Toggles the active option without closing the listbox.' },
      { keys: 'Backspace', action: 'Removes the final selected value when the editable query is empty.' },
      { keys: 'Escape', action: 'Closes the listbox without changing selected values.' },
      { keys: 'Tab', action: 'Closes the listbox and continues normal tab navigation.' },
    ],
    notes: [
      'Follows the WAI-ARIA editable combobox pattern: focus stays on the input and aria-activedescendant identifies the active option.',
      'The listbox sets aria-multiselectable=true; selected options set aria-selected=true and are also represented as removable tags.',
      'The listbox portals to document.body, flips and clamps through the shared anchored-position engine, and closes on an outside press.',
      'Renders one hidden input per selected value when name is set so a native form preserves multiplicity.',
      'Reads id, aria-describedby, and aria-invalid from a surrounding Field when present.',
    ],
  },
  motion: {
    description: 'The suggestion panel fades and scales in from the control edge; motion is disabled when reduced motion is preferred.',
    transition: { speed: 'fast', ease: 'out' },
  },
};