import type { ComponentSpec } from '../schema.ts';
import { token } from '../vocab.ts';
import { playerDensities, playerRepeatModes } from './player-card.ts';
import { volumeReadouts } from './volume-bar.ts';

/** Where the strip is docked, which decides which edge carries its hairline. */
export const playerBarPositions = ['docked', 'floating'] as const;

export const playerBarSpec: ComponentSpec = {
  name: 'PlayerBar',
  id: 'player-bar',
  category: 'organism',
  status: 'draft',
  summary:
    'The whole player on one line: what is playing on the leading edge, the transport and its seek bar through the middle, and the output controls - actions, volume, format - on the trailing edge.',
  element: 'div',
  anatomy: [
    { name: 'bar', description: 'The strip itself, a full-width chrome surface rather than a card.', required: true },
    { name: 'track', description: 'A TrackInfo block: the cover and what is playing.', required: true },
    { name: 'transport', description: 'A TransportControls row, centred over the scrubber.', required: true },
    { name: 'scrubber', description: 'The seek row under the transport: elapsed, the SeekBar, and the time remaining.', required: true },
    { name: 'rails', description: 'The ends of the transport row: what belongs to the track being played rather than to the output - the heart, the fader, and whatever the app hangs there. Both are drawn, empty or not, so the transport stays centred on the strip.' },
    { name: 'favorite', description: 'A heart, filled once saved. Drawn only when the strip has somewhere to save to.' },
    { name: 'actions', description: 'Caller-supplied buttons on the trailing edge - a queue, an equaliser, whatever the app has.' },
    { name: 'volume', description: 'A VolumeBar in its popover layout: a speaker on the trailing rail, and the standing fader behind it.' },
    { name: 'status', description: 'A quiet line under the volume for what the output is doing - sample rate, channel count, device.' },
  ],
  props: [
    { name: 'artwork', type: 'node', description: 'Album art, forwarded to the TrackInfo block.' },
    { name: 'title', type: 'node', description: 'What is playing.' },
    { name: 'subtitle', type: 'node', description: 'A second line, usually the album.' },
    { name: 'album', type: 'node', description: 'A third line, usually the artist.' },
    { name: 'duration', type: 'number', required: true, description: 'Track length in seconds.' },
    { name: 'value', type: 'number', description: 'Controlled playhead position in seconds.' },
    { name: 'defaultValue', type: 'number', default: 0, description: 'Initial position when uncontrolled.' },
    { name: 'onValueChange', type: 'handler', description: 'Called with the position in seconds as the user scrubs or keys.' },
    { name: 'onSeekEnd', type: 'handler', description: 'Called once with the final position when a scrub is released.' },
    { name: 'playing', type: 'boolean', description: 'Controlled play state.' },
    { name: 'defaultPlaying', type: 'boolean', default: false, description: 'Initial play state when uncontrolled.' },
    { name: 'onPlayingChange', type: 'handler', description: 'Called with the new play state when play/pause is pressed.' },
    { name: 'onStop', type: 'handler', description: 'Called when stop is pressed. Omit it and the control is not rendered.' },
    { name: 'onSkipBack', type: 'handler', description: 'Called when previous is pressed. Omit it and the control is not rendered.' },
    { name: 'onSkipForward', type: 'handler', description: 'Called when next is pressed. Omit it and the control is not rendered.' },
    { name: 'shuffle', type: 'boolean', description: 'Controlled shuffle state.' },
    { name: 'defaultShuffle', type: 'boolean', default: false, description: 'Initial shuffle state when uncontrolled.' },
    { name: 'onShuffleChange', type: 'handler', description: 'Called with the new shuffle state. Omit both this and shuffle to drop the control.' },
    { name: 'repeat', type: 'enum', values: playerRepeatModes, description: 'Controlled repeat mode.' },
    { name: 'defaultRepeat', type: 'enum', values: playerRepeatModes, default: 'off', description: 'Initial repeat mode when uncontrolled.' },
    { name: 'onRepeatChange', type: 'handler', description: 'Called with the next mode as repeat cycles. Omit both this and repeat to drop the control.' },
    { name: 'favorite', type: 'boolean', description: 'Controlled favourite state.' },
    { name: 'defaultFavorite', type: 'boolean', default: false, description: 'Initial favourite state when uncontrolled.' },
    { name: 'onFavoriteChange', type: 'handler', description: 'Called with the new favourite state. Omit both this and favorite to drop the heart - a strip that cannot save anything should not offer to.' },
    { name: 'volume', type: 'number', description: 'Controlled fader position, 0-100.' },
    { name: 'defaultVolume', type: 'number', default: 70, description: 'Initial fader position when uncontrolled - 70, which is -18dB.' },
    { name: 'onVolumeChange', type: 'handler', description: 'Called with the 0-100 fader position. Omit both this and volume to drop the fader entirely.' },
    { name: 'muted', type: 'boolean', description: 'Controlled mute state.' },
    { name: 'defaultMuted', type: 'boolean', default: false, description: 'Initial mute state when uncontrolled.' },
    { name: 'onMutedChange', type: 'handler', description: 'Called with the new mute state.' },
    { name: 'volumeReadout', type: 'enum', values: volumeReadouts, default: 'none', description: "What the fader's readout prints; forwarded to the VolumeBar. None on a strip: the fader is behind a button here, and a panel opened to move one thing should hold one thing." },
    { name: 'leading', type: 'node', description: 'Controls on the rail before the transport, level with it - lyrics, a like, whatever belongs to the track.' },
    { name: 'trailing', type: 'node', description: 'Controls on the rail after the transport, before the fader.' },
    { name: 'actions', type: 'node', description: 'Buttons on the trailing edge, before the fader. A slot rather than props, because a queue button with a count on it is the app\'s idea, not the kit\'s.' },
    { name: 'status', type: 'node', description: 'A quiet line under the fader for what the output is doing.' },
    { name: 'position', type: 'enum', values: playerBarPositions, default: 'docked', description: 'Docked sits flush against the window with a hairline on its leading edge; floating rounds its corners and lifts on a shadow.' },
    { name: 'density', type: 'enum', values: playerDensities, default: 'compact', description: 'How tightly the strip is packed. Compact by default: a strip is chrome, and chrome should cost as little height as it can.' },
    { name: 'remaining', type: 'boolean', default: true, description: 'Counts the trailing clock down as -4:42 rather than printing the total. A strip is read while listening, when what is left matters more than how long it was.' },
    { name: 'shape', type: 'string', description: "The seek bar's shape; forwarded straight through." },
    { name: 'tone', type: 'string', description: "The seek bar's colour family; forwarded straight through." },
    { name: 'fill', type: 'string', description: "How the seek bar's played run is filled; forwarded straight through." },
    { name: 'levels', type: 'array', item: { type: 'number', description: 'One normalized 0-1 loudness sample.' }, description: "The seek bar's loudness samples; forwarded straight through." },
    { name: 'beat', type: 'object', description: "The seek bar's live beat state; forwarded straight through, so the strip's bar deforms with the music." },
    { name: 'intensity', type: 'number', description: 'How hard the beat deforms the seek bar; forwarded straight through.' },
    { name: 'tracer', type: 'boolean', default: true, description: "Draws the seek bar's tracer, the shadow trailing the beat. On, as on a card: the bar is the only moving thing on the strip. Idle without a `beat`." },
    { name: 'formatTime', type: 'handler', description: 'Formats both clocks. Defaults to m:ss, or h:mm:ss past an hour.' },
    { name: 'disabled', type: 'boolean', default: false, description: 'Dims the strip and blocks every control.' },
    { name: 'skeleton', type: 'boolean', default: false, description: 'Loads every part as its own placeholder, keeping the strip at its exact height and layout.' },
    { name: 'labels', type: 'object', description: 'Overrides the control labels; merged over the English defaults.' },
  ],
  defaults: {
    defaultValue: 0, defaultPlaying: false, defaultShuffle: false, defaultRepeat: 'off',
    defaultFavorite: false, defaultVolume: 70, defaultMuted: false, volumeReadout: 'none',
    position: 'docked', density: 'compact', remaining: true, tracer: true, disabled: false, skeleton: false,
  },
  dimensions: {
    gap: token('space-4'),
    paddingInline: token('space-4'),
    paddingBlock: token('space-3'),
    border: token('border-subtle'),
  },
  states: [
    { name: 'default', description: 'Three regions on one line: what is playing, the transport over its scrubber, and the output controls.' },
    {
      name: 'narrow',
      description: 'Below the width the three regions need, the output column drops out first and then the track block, because a strip that cannot show its transport is not a player any more.',
      tokens: { surface: token('surface') },
    },
    { name: 'disabled', description: 'Halved opacity; the seek bar and every control ignore input.' },
    { name: 'skeleton', description: 'Every region loads as its own placeholder, so the strip holds the exact height it will settle into rather than collapsing.' },
  ],
  paint: { background: token('surface'), text: token('text'), border: token('border-subtle') },
  transition: { duration: token('duration-fast'), ease: token('ease-out') },
  tokens: [
    'space-1', 'space-2', 'space-3', 'space-4', 'radius-lg', 'shadow-3',
    'surface', 'border-subtle', 'text', 'text-muted', 'text-subtle',
    'accent-solid', 'accent-contrast', 'accent-text',
    'font-size-xs', 'duration-fast', 'ease-out',
  ],
  a11y: {
    role: 'group',
    focusable: false,
    keyboard: [
      { keys: 'Tab', action: 'Moves through the seek bar, the transport, the actions, and the fader in reading order.' },
      { keys: 'Space, Enter', action: 'Activates the focused control.' },
      { keys: 'Arrows, Home, End', action: 'Scrub the seek bar, or move the fader, whichever holds focus.' },
    ],
    notes: [
      'The strip is a group labelled by its title, so a screen reader announces what is playing before reading the controls.',
      'The transport and the fader are each their own labelled group inside it, so the two are told apart without having to infer it from the button names.',
      'Both clocks are decorative - the seek bar already speaks the position through aria-valuetext - so neither is announced.',
      'The strip is chrome, not the page: it takes no focus itself, so tabbing into a document never lands here first.',
    ],
  },
  motion: {
    description: 'Nothing on the strip animates but the controls under a press and the seek bar under the music. The clocks and the layout never ease, so the readouts cannot appear to lag the audio.',
    press: true,
    transition: { speed: 'fast', ease: 'out' },
  },
};
